### ISSUE TITLE
Parse does not work if there is a line comment

### ISSUE THREAD

**Issue by mk3008** [mk3008/Carbunql#341]
sample
```sql
with
dat(id) as ( 
    values
    (1)
    --comment
)
select * from dat
```

result
```
Carbunql.Analysis.SyntaxException: expect ')', actual 'select'
   at Carbunql.Analysis.ITokenReaderExtension.Read(ITokenReader source, String expect)
   at Carbunql.Analysis.Parser.VirtualTableParser.Parse(ITokenReader r)
   at Carbunql.Analysis.Parser.CommonTableParser.Parse(ITokenReader r)
   at Carbunql.Analysis.Parser.WithClauseParser.ParseCommonTables(ITokenReader r)+MoveNext()
   at System.Collections.Generic.List`1[[Carbunql.Clauses.CommonTable, Carbunql, Version=0.6.1.1, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 )
   at System.Linq.Enumerable.ToList[CommonTable](IEnumerable`1 source)
   at Carbunql.Analysis.Parser.WithClauseParser.Parse(ITokenReader r)
   at Carbunql.Analysis.Parser.CTEQueryParser.Parse(ITokenReader r)
   at Carbunql.Analysis.QueryParser.Parse(ITokenReader r)
   at Carbunql.Analysis.QueryParser.Parse(String text)
   at CarbunqlWeb.Pages.Format.OnChange(String value)
```

**Comment by mk3008** [comment]
It is reproduced on the demo site, but not on the main branch.
However, we were able to identify suspicious areas.

```sql
select 1+--
2
````

If symbols are used consecutively like this, they will be analyzed like this.
```sql
SELECT
     1 +-- 2
````

Expect the following.
```sql
SELECT
     1 + 2
````

**Comment by mk3008** [comment]
The +-- lexeme problem is solved, but the sample code is not.

```sql
with
dat(id) as (
     values
     (1)
     --comment
)
select * from dat
````

I couldn't reproduce it in code, but maybe it's because the line break code isn't recognized correctly?
We will continue to respond.
